<a href="https://www.kaggle.com/code/kalalshivagoud/numpy-part-2?scriptVersionId=257269785" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import time

addition of number's

In [2]:
initial_time=time.time()
a=0
for i in range(100000):
    a=a+i
print(a)
final_time=time.time()
result=final_time-initial_time
print(result)

4999950000
0.013482332229614258


**addition of numbers with numpy array**

In [3]:
initial_time=time.time()
n=np.arange(1000)
s=np.sum(n)
print(s)
final_time=time.time()
result1=final_time-initial_time
print(result1)

499500
0.0034215450286865234


In [4]:
diffrence=(result1-result)
print(diffrence)

-0.010060787200927734


**create random number array**

In [5]:
import numpy as np

In [6]:
s=np.random.rand(3)
s

array([0.45765378, 0.83772984, 0.62840376])

**know the data type using dtype attribute**

In [7]:
n=np.array([1,2,3],dtype=float)
n.dtype
n

array([1., 2., 3.])

**complex array**

In [8]:
c=np.array([1+3j , 3+4j])
c.dtype

dtype('complex128')

**boolean array**

In [9]:
d=np.array([True,False])
d.dtype

dtype('bool')

**Indexing**

In [10]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a[6]

6

In [12]:
b=np.array([1,2,3])
b
b[-1]

3

Slicing

In [13]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[1:10:2]  #[start_index:last_index(exclusive):step]

array([1, 3, 5, 7, 9])

**Boolean Indexing**

**Assignment:filter the array with only odd numbers**

In [15]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a%2!=0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
mask=(a%2!=0)  #mask is  a boolean array,will return "true" values
a[mask]

array([1, 3, 5, 7, 9])

**Basic operations**

In [18]:
a=np.array([1,2,3])
a-1

array([0, 1, 2])

In [19]:
a*2

array([2, 4, 6])

In [20]:
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [21]:
a*b

array([ 4, 10, 18])

In [22]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

element wise multiplication-array must be of same size,corresponding element multiplication will happen

In [23]:
a=np.array([[[1,2,3],
            [2,3,4],
            [5,7,9]]])
a

array([[[1, 2, 3],
        [2, 3, 4],
        [5, 7, 9]]])

In [24]:
b=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
a*b

array([[[ 1,  4,  9],
        [ 8, 15, 24],
        [35, 56, 81]]])

In [26]:
import numpy as np

**Dot product** 
suppose a=a1,a2,a3
b=b1,b2,b3
a.b=a1b1+a2b2+a3b3

In [27]:
c=np.random.rand(5)
d=np.random.rand(5)
c
d

array([0.61145158, 0.39941361, 0.53749911, 0.49044054, 0.37915765])

In [28]:
c.dot(d)

1.1161367954051757

**2-D array**
For multipying two matrices the required condition is,
**no.of columns of first_matrix=no.of rows of second_matrix**

In [29]:
p=np.array([[1,2,3],
            [4,5,6]])
q=np.array([[[1,3,5],
             [4,7,9],
             [5,3,8]]])
p.dot(q)  # q.dot(p) will not work since no.of columns of q and no.of rows of p are not equal

array([[[ 24,  26,  47]],

       [[ 54,  65, 113]]])

**Array comparison**

In [30]:
import numpy as np


In [31]:
a=np.random.randint(5)
b=np.random.randint(5)
a==b

False

In [32]:
c = np.array([12,45,36,78])
d = np.array([12,5,45,7])

In [33]:
c==d  #element wise comparison

array([ True, False, False, False])

**array_equal() method**

In [34]:
mask=(c==d)

In [35]:
c[mask]

array([12])

In [36]:
np.array_equal(c,d)

False

**Logical Operator**

In [37]:
k=np.array([1,0,0,3])
l=np.array([1,0,1,0])

In [38]:
np.logical_and(k,l)  #two conditions should true for "AND" operator

array([ True, False, False, False])

In [39]:
np.logical_or(k,l) #alteast  one condition is true for "OR" operator

array([ True, False,  True,  True])

In [40]:
m=np.array([1,2,3])


In [41]:
np.sum(m)


6

In [42]:
np.mean(m)

2.0

In [43]:
np.max(m)

3

In [44]:
np.min(m)

1

In [45]:
np.argmin(m)

0

In [46]:
np.argmax(m)

2

In [47]:
np.median(m)

2.0

**2-d array**

In [48]:
a=np.array([[1,7,5],[3,6,8]])

In [49]:
np.sum(a,axis=0)  #row wise

array([ 4, 13, 13])

In [50]:
np.sum(a,axis=1)  #column wise

array([13, 17])

In [51]:
np.min(a,axis=0)

array([1, 6, 5])

In [52]:
a=np.array([True,False,True])
b=np.array([1,2,3])

In [53]:
np.any(a)  # any value in the argument should be true

True

In [54]:
np.all(a) #all values in the argument should be true

False

In [55]:
np.all(b>0)

True

**Assignment**

In [56]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])

#x<y<z

In [57]:
res1=x<y
res1

array([ True,  True,  True])

In [58]:
res2=y<z
res2

array([ True,  True,  True])

In [59]:
final_result=res1&res2
final_result

array([ True,  True,  True])