<a href="https://www.kaggle.com/code/kalalshivagoud/numpy-part-3?scriptVersionId=257269463" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**1-D to 2-d**

**Tile function**-constructs a new array by repeating array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
b=np.tile(a,(3,1))
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [4]:
c=np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [5]:
np.tile(c,(2,2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

**Convert 1-D to 2-D**

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=a[0:3,np.newaxis]
b.shape


(3, 1)

**broadcasting**

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b=np.array([1,2,0])

In [10]:
a+b

array([[ 2,  4,  3],
       [ 5,  7,  6],
       [ 8, 10,  9]])

**flattening**

In [11]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.ravel(a)   #convert into 1D array

array([1, 2, 3, 4, 5, 6])

**Transpose**:Convert rows as columns and wise versa

In [13]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
np.trace(a)

15

In [16]:
#reshape()

**sort**

In [17]:
a=np.random.randint(1,20,10)
a

array([ 4, 14, 11,  3,  2,  9, 13, 15,  5,  1])

In [18]:
a=np.sort(a)
a

array([ 1,  2,  3,  4,  5,  9, 11, 13, 14, 15])

In [19]:
a=a[::-1]
a


array([15, 14, 13, 11,  9,  5,  4,  3,  2,  1])